# Generated by Django 3.2.11 on 2022-01-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('picture', models.ImageField(upload_to='app/static/app/uploads/img/members/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('club_member_number', models.PositiveIntegerField()),
                ('date_of_issue_vog', models.DateField(blank=True, null=True)),
                ('knsa_member_number', models.PositiveIntegerField(blank=True, null=True)),
                ('shooting_count', models.PositiveIntegerField()),
                ('member_since', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('payment_method', models.PositiveIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('picture', models.ImageField(upload_to='app/static/app/uploads/img/products/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('code', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_picture_url', models.CharField(max_length=500)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(blank=True, max_length=100, null=True)),
                ('product_code', models.PositiveIntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
    ]
